
#
# how may output time steps (usually in hours) in each model run
#
modlength = {'WAM4': 67, 'WAM10':67, 'AROME':67, 'HIRLAM8':67, 'LAWAM':67, 'ECWAM':241, 'MWAM4':67, 'MWAM8':241, 'EXP':67, 'WAMAROME2W':67, 'WAMAROME1W':67}

#
#  Variable dictionaries for each model
#

d22 = {'Hs':  {'standard_name': 'sea_surface_wave_significant_height',
               'short_name': 'significant wave height' ,
               'units': 'm'},
       'Tp':  {'standard_name': 'sea_surface_wave_period_at_variance_spectral_density_maximum',
               'short_name': 'peak period',
               'units': 's'},
       'Tm02':{'standard_name': 'sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment',
               'short_name': 'mean period',
               'units': 's'},
       'DDP': {'standard_name': 'sea_surface_wind_wave_from_direction',
               'short_name': 'peak direction',
               'units': 'degree',
               'convention': 'meteorological'},
       'DDM': {'standard_name': 'sea_surface_wind_wave_from_direction',
               'short_name': 'mean direction',
               'units': 'degree',
               'convention': 'meteorological'},
       'FF':  {'standard_name': 'wind_speed',
               'short_name': 'wind speed', 
               'units': 'm/s'},
       'DD': {'standard_name': 'wind_from_direction', 
              'short_name' : 'wind direction',
              'units': 'degree',
              'convention': 'meteorological'}} 

MWAM4 = {'Hs':    {'standard_name': 'sea_surface_wave_significant_height',
                   'short_name': 'significant wave height',
                   'units': 'm',
                   'model_name': 'hs'},
         'Tp':    {'standard_name': 'sea_surface_wave_period_at_variance_spectral_density_maximum',
                   'short_name': 'peak period',
                   'units': 's',
                   'model_name': 'tp'},
         'Tm02':  {'standard_name': 'sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment',
                   'short_name': 'mean period',
                   'units': 's',
                   'model_name': 'tm2'},
         'DDM':   {'standard_name': 'sea_surface_wave_to_direction',
                   'short_name': 'mean direction',
                   'units': 'degree',
                   'model_name': 'thq',
                   'convention': 'oceanographic'},
         'Hs_s':  {'standard_name': 'sea_surface_swell_wave_significant_height',
                   'short_name': 'swell significant wave height',
                   'units': 'm',
                   'model_name': 'hs_swell'},
         'Tp_s':  {'standard_name': 'sea_surface_swell_wave_period',
                   'short_name': 'swell peak period', 
                   'units': 's',
                   'model_name': 'tp_swell'},
         'Tm02_s':{'standard_name': 'sea_surface_swell_wave_mean_period_from_variance_spectral_density_second_frequency_moment',
                   'short_name': 'swell mean period',
                   'units': 's',
                   'model_name': 'tm2_swell'},
         'DDM_s': {'standard_name': 'sea_surface_swell_wave_from_direction',
                   'short_name': 'swell mean direction',
                   'units': 'degree',
                   'model_name': 'thq_swell',
                   'convention': 'oceanographic'},
         'FF':    {'standard_name': 'wind_speed',
                   'short_name': 'wind speed',
                   'units': 'm/s',
                   'model_name': 'ff'},
         'DD':    {'standard_name': 'wind_from_direction',
                   'short_name': 'wind direction',
                   'units': 'degree',
                   'model_name': 'dd',
                   'convention':  'oceanographic'}} 

MWAM8 = {'Hs':    {'standard_name': 'sea_surface_wave_significant_height',
                   'short_name': 'significant wave height',
                   'units': 'm',
                   'model_name': 'VHM0'},
         'Tp':    {'standard_name': 'sea_surface_wave_period_at_variance_spectral_density_maximum',
                   'short_name': 'peak period',
                   'units': 's',
                   'model_name': 'VTPK'},
         'Tm02':  {'standard_name': 'sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment',
                   'short_name': 'mean period',
                   'units': 's',
                   'model_name': 'VTM02'},
         'DDM':   {'standard_name': 'sea_surface_wave_to_direction',
                   'short_name': 'mean direction',
                   'units': 'degree',
                   'model_name': 'VMDR',
                   'convention': 'oceanographic'},
         'Hs_s':  {'standard_name': 'sea_surface_swell_wave_significant_height',
                   'short_name': 'swell significant wave height',
                   'units': 'm',
                   'model_name': 'VHM0_SW'},
         'Tp_s':  {'standard_name': 'sea_surface_swell_wave_period',
                   'short_name': 'swell peak period', 
                   'units': 's',
                   'model_name': 'VTPK_SW'},
         'Tm02_s':{'standard_name': 'sea_surface_swell_wave_mean_period_from_variance_spectral_density_second_frequency_moment',
                   'short_name': 'swell mean period',
                   'units': 's',
                    'model_name': 'VTM02_SW'},
         'DDM_s': {'standard_name': 'sea_surface_swell_wave_from_direction',
                   'short_name': 'swell mean direction',
                   'units': 'degree',
                   'model_name': 'VMDR_SW',
                   'convention': 'oceanographic'},
         'FF':    {'standard_name': 'wind_speed',
                   'short_name': 'wind speed',
                   'units': 'm/s',
                   'model_name': 'ff'},
         'DD':    {'standard_name': 'wind_from_direction',
                   'short_name': 'wind direction',
                   'units': 'degree',
                   'model_name': 'dd',
                   'convention':  'oceanographic'}} 


EXP=MWAM4

ECWAM =    {'Hs':    {'standard_name': 'sea_surface_wave_significant_height',
                      'short_name': 'significant wave height',
                      'units': 'm',
                      'model_name': 'significant_wave_height'},
            'Tp':    {'standard_name': 'sea_surface_wave_period_at_variance_spectral_density_maximum',
                      'short_name': 'peak period',
                      'units': 's',
                      'model_name': 'peak_wave_period'},
            'Tm02':  {'standard_name': 'sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment',
                      'short_name': 'mean period',
                      'units': 's',
                      'model_name': 'mean_wave_period'},
            'DDM':   {'standard_name': 'sea_surface_wave_to_direction',
                      'short_name': 'mean direction',
                      'units': 'degree',
                      'model_name': 'wave_direction',
                      'convention': 'oceanographic'},
            'Hs_s':  {'standard_name': 'sea_surface_swell_wave_significant_height',
                      'short_name': 'swell significant wave height',
                      'units': 'm',
                      'model_name': 'significant_swell_wave_height'},
            'Tm02_s':{'standard_name': 'sea_surface_swell_wave_mean_period_from_variance_spectral_density_second_frequency_moment',
                      'short_name': 'swell mean period',
                      'units': 's',
                      'model_name': 'sea_surface_swell_wave_period'}, # or is this Tp_s ?
            'DDM_s': {'standard_name': 'sea_surface_swell_wave_from_direction', 
                      'short_name': 'swell mean direction',
                      'units': 'degree',
                      'model_name': 'sea_surface_swell_wave_to_direction',
                      'convention': 'oceanographic'}}


LAWAM = ECWAM

AROME = {'FF': {'standard_name': 'wind_speed', 
                'short_name': 'wind speed',
                'units': 'm/s',
                'model_name': 'None'},
         'DD': {'standard_name': 'wind_from_direction', 
                'short_name': 'wind direction', 
                'units': 'degree', 
                'model_name': 'None', 
                'convention': 'meteorological'}}



