#!/bin/bash -fxe
#$ -N waveverification
#$ -l h_rt=2:00:00
#$ -S /bin/bash
#$ -pe mpi 1
#$ -q ded-parallel.q
#$ -M johannesro@met.no
#$ -m abe
#$ -o /lustre/storeA/project/fou/hi/waveverification/logs/
#$ -cwd 
#$ -j y
# ---------------------------

echo "Got $NSLOTS slots."

#export R_LIBS=/modules/trusty/R/3.2.1/lib/R

cd /home/johannesro/waveverification 

touch test1.txt
touch /home/johannesro/waveverification/test2.txt

# gather data
./collectdata.py > /home/johannesro/waveverification/collectdata.log

# make plots
./validate.py > /home/johannesro/waveverification/validate.log

# update webpage
cd /lustre/storeA/project/fou/hi/waveverification/website

./makepage.sh 
./makepage_DD.sh 
./makeindex.sh 

# upload webpage
cd /lustre/storeA/project/fou/hi/waveverification
./upload.sh



